## Python-Numpy vectors

In [1]:
import numpy as np

### This isn't row/column Vector ==> Don't use this!

In [2]:
a = np.random.randn(5)    

In [3]:
a

array([ 0.81422873, -1.38405491,  1.56047917, -0.81281588, -0.52126295])

In [4]:
a.shape     # rank of Array 

(5,)

In [5]:
print(a)

[ 0.81422873 -1.38405491  1.56047917 -0.81281588 -0.52126295]


In [6]:
type(a)

numpy.ndarray

In [7]:
a_t = a.T     # Transpose of the array

In [8]:
print(a_t)     # a_t = a

[ 0.81422873 -1.38405491  1.56047917 -0.81281588 -0.52126295]


In [9]:
a_t.shape

(5,)

In [10]:
np.dot(a, a_t)

5.9460564004080485

## This is a Matrix  ==> Use this!

In [11]:
vc = np.random.randn(5, 1)     
vc

array([[-1.81751227],
       [ 2.34681884],
       [-0.35007496],
       [ 2.62962   ],
       [-0.89867879]])

In [12]:
print(vc)

[[-1.81751227]
 [ 2.34681884]
 [-0.35007496]
 [ 2.62962   ]
 [-0.89867879]]


In [13]:
vc.shape     

(5, 1)

In [14]:
vc_t = vc.T
vc_t

array([[-1.81751227,  2.34681884, -0.35007496,  2.62962   , -0.89867879]])

In [15]:
print(vc_t)

[[-1.81751227  2.34681884 -0.35007496  2.62962    -0.89867879]]


In [16]:
vc_t.shape

(1, 5)

In [17]:
vr = np.random.randn(1, 5)
print(vr)

[[-0.77103103 -0.28108874  2.0107465  -0.09966679  0.11463837]]


In [18]:
vr.shape

(1, 5)

In [19]:
print("Type of a:", type(a))
print("Shape of a:", a.shape)

Type of a: <class 'numpy.ndarray'>
Shape of a: (5,)


In [20]:
print("Type of vc:", type(vc))
print("Shape of vc:", vc.shape)

Type of vc: <class 'numpy.ndarray'>
Shape of vc: (5, 1)


In [21]:
print("Type of vr:", type(vr))
print("Shape of vr:", vr.shape)

Type of vr: <class 'numpy.ndarray'>
Shape of vr: (1, 5)


In [22]:
p = np.dot(vc, vc.T)
print(p)

[[ 3.30335087 -4.26537205  0.63626554 -4.77936663  1.63335973]
 [-4.26537205  5.50755868 -0.82156251  6.17124177 -2.10903632]
 [ 0.63626554 -0.82156251  0.12255248 -0.92056412  0.31460494]
 [-4.77936663  6.17124177 -0.92056412  6.91490136 -2.36318372]
 [ 1.63335973 -2.10903632  0.31460494 -2.36318372  0.80762357]]


In [23]:
type(p)

numpy.ndarray

In [24]:
p.shape

(5, 5)

### Ensure dimension (Assert)

In [25]:
print(a.shape == (5, 1))

False


In [26]:
print(vc.shape == (5, 1))

True


In [27]:
print(vr.shape == (1, 5))

True


### Reshape of Rank of a Array to a Vector (Matrix)

In [28]:
a.shape

(5,)

In [29]:
print(a.shape == (5, ))

True


In [30]:
a = a.reshape(5,1)

In [31]:
a.shape

(5, 1)

In [32]:
type(a)

numpy.ndarray

In [33]:
print(a.shape == (5, 1))

True


In [34]:
print(a.shape == (5, ))

False


In [35]:
print(a.shape == (1, 5))

False


In [37]:
a

array([[ 0.81422873],
       [-1.38405491],
       [ 1.56047917],
       [-0.81281588],
       [-0.52126295]])

In [38]:
print(a)

[[ 0.81422873]
 [-1.38405491]
 [ 1.56047917]
 [-0.81281588]
 [-0.52126295]]
