# Broadcasting

In [1]:
import numpy as np

In [2]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [3]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
A.shape

(3, 4)

In [5]:
calery = A.sum(axis = 0)     # vertical
print(calery)

[ 59.  239.  155.4  76.9]


In [6]:
percentage = 100 * A / calery.reshape(1, 4)     # Broadcasting of calery from (1, 4) to (3, 4):
# [[59.  239.  155.4  76.9]
#  [59.  239.  155.4  76.9]
#  [59.  239.  155.4  76.9]]
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [7]:
calery.shape

(4,)

In [8]:
calery

array([ 59. , 239. , 155.4,  76.9])

In [14]:
calery = calery.reshape(1, 4)

In [15]:
calery.shape

(1, 4)

In [16]:
calery

array([[ 59. , 239. , 155.4,  76.9]])